name: Build and Release Plugin

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer (no dev)
        run: composer install --no-dev --prefer-dist --no-progress
        working-directory: .

      - name: Optimize autoloader
        run: composer dump-autoload -o --no-dev
        working-directory: .

      - name: Build zip
        run: |
          set -e
          ZIP="benhughes-gf-wc-${GITHUB_REF_NAME}.zip"
          STAGE="build/benhughes-gf-wc"
          mkdir -p "$STAGE"
          rsync -a ./ "$STAGE" \
            --exclude '/build' \
            --exclude '/.git' \
            --exclude '/.github' \
            --exclude '/.idea' \
            --exclude '/node_modules' \
            --exclude '/.eslintrc*' \
            --exclude '/.eslintignore' \
            --exclude '/JS-TESTING-README.md' \
            --exclude '/JAVASCRIPT-TESTING-SETUP.md' \
            --exclude '/LINTING-FIXES-NEEDED.md' \
            --exclude '/ARCHITECTURE.md' \
            --exclude '/.claude' \
            --exclude '/.gitignore' \
            --exclude '/ROADMAP*.md' \
            --exclude '/MERGE-SUMMARY.md' \
            --exclude '/PROJECT-STATUS.md'
          cd build
          zip -r "$ZIP" benhughes-gf-wc
          echo "ZIP_PATH=build/$ZIP" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
